### ISSUE TITLE
[Bug] The gem downloading is not fetches recent changes

### ISSUE THREAD

**Issue by Fattaf** [rootstrap/apple_auth#32]
When I download the current gem into my project, I get the gem version tagged as 1.0.0, which differs greatly from the main branch. 

Please, bump a new tag pointing to the current main branch. 

Thank you.

**Comment by TimoPeraza** [comment]
Hi Fattaf,

We want to apologize to you and the community because we haven't been paying enough attention to this gem. We are reorganizing our team to be able to maintain it properly. [Here](https://rubygems.org/gems/apple_auth/versions/1.1.0) you can find the new version with the last changes,

Sorry again and regards.
